[theme]
primaryColor = "#2878F3"            # your sidebar & calendar‐button blue
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
headless = true
port = 8503
enableCORS = false
